In [108]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [109]:
import numpy as np
from cuda import *
from tensor import *

In [110]:
a = np.random.randn(2,2)
get_numpy_stride(a), get_numpy_stride(np.ascontiguousarray(a.T)), stride_from_shape(a.T.shape)

((2, 1), (2, 1), (2, 1))

In [111]:
t = Tensor.from_numpy(a.T).cuda()
t.numpy()

array([[-1.79221628, -2.73591457],
       [ 0.75255623, -0.01387382]])

In [112]:
np.exp(a.T*a.T + 4) == (t*t + 4).exp().numpy()

array([[False,  True],
       [ True,  True]])

In [113]:
t.contiguous().numpy() == t.numpy()

array([[ True,  True],
       [ True,  True]])